CREATE TABLE `control_plane_fleet_cleanup_authority` (
  `id` VARCHAR(191) NOT NULL,
  `organizationId` VARCHAR(32) NOT NULL,
  `installationId` VARCHAR(32) NOT NULL,
  `repositoryId` BIGINT NOT NULL,
  `repositoryFullName` VARCHAR(191) NOT NULL,
  `sourceSha` CHAR(40) NOT NULL,
  `treeSha` CHAR(40) NOT NULL,
  `issuanceDigest` VARCHAR(71) NOT NULL,
  `inventoryDigest` VARCHAR(71) NOT NULL,
  `planDigest` VARCHAR(71) NOT NULL,
  `chainHeadDigest` VARCHAR(71) NULL,
  `fileActionSetDigest` VARCHAR(71) NOT NULL,
  `authorityRevision` VARCHAR(127) NOT NULL,
  `generation` INTEGER NOT NULL DEFAULT 1,
  `state` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  `activeExecutionKey` VARCHAR(71) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `cp_fleet_cleanup_authority_binding_key` (`repositoryId`, `issuanceDigest`, `inventoryDigest`, `planDigest`, `sourceSha`),
  INDEX `cp_fleet_cleanup_authority_repo_state` (`repositoryId`, `state`, `updatedAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `control_plane_fleet_cleanup_capability` (
  `id` VARCHAR(191) NOT NULL,
  `authorityId` VARCHAR(191) NOT NULL,
  `issueNumber` INTEGER NOT NULL,
  `approvalScopeDigest` VARCHAR(71) NOT NULL,
  `issuance` JSON NOT NULL,
  `plan` JSON NOT NULL,
  `fileActionSet` JSON NOT NULL,
  `fileActionSetDigest` VARCHAR(71) NOT NULL,
  `replacementFiles` JSON NOT NULL,
  `replacementFilesDigest` VARCHAR(71) NOT NULL,
  `action` VARCHAR(32) NOT NULL DEFAULT 'READY_PR_ONLY',
  `state` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  `requestId` VARCHAR(191) NOT NULL,
  `requestDigest` VARCHAR(71) NOT NULL,
  `approvedBy` VARCHAR(128) NOT NULL,
  `approvedAt` DATETIME(3) NOT NULL,
  `expiresAt` DATETIME(3) NOT NULL,
  `consumedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `cp_fleet_cleanup_capability_request_key` (`requestId`),
  INDEX `cp_fleet_cleanup_capability_scope_idx` (`authorityId`, `approvalScopeDigest`, `issueNumber`),
  INDEX `cp_fleet_cleanup_capability_state_expiry` (`state`, `expiresAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `cp_fleet_cleanup_capability_authority_fkey` FOREIGN KEY (`authorityId`) REFERENCES `control_plane_fleet_cleanup_authority` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `control_plane_fleet_cleanup_execution` (
  `id` VARCHAR(191) NOT NULL,
  `authorityId` VARCHAR(191) NOT NULL,
  `capabilityId` VARCHAR(191) NOT NULL,
  `executionKey` VARCHAR(71) NOT NULL,
  `reservationId` VARCHAR(127) NOT NULL,
  `organizationId` VARCHAR(32) NOT NULL,
  `installationId` VARCHAR(32) NOT NULL,
  `issuanceDigest` VARCHAR(71) NOT NULL,
  `inventoryDigest` VARCHAR(71) NOT NULL,
  `planDigest` VARCHAR(71) NOT NULL,
  `runId` VARCHAR(127) NOT NULL,
  `workerId` VARCHAR(127) NOT NULL,
  `repositoryId` BIGINT NOT NULL,
  `repositoryFullName` VARCHAR(191) NOT NULL,
  `sourceSha` CHAR(40) NOT NULL,
  `issueNumber` INTEGER NOT NULL,
  `chainHeadDigest` VARCHAR(71) NULL,
  `expectedStateGeneration` INTEGER NOT NULL,
  `reservedStateGeneration` INTEGER NOT NULL,
  `executionGeneration` INTEGER NOT NULL DEFAULT 1,
  `state` VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
  `leaseTokenDigest` CHAR(64) NOT NULL,
  `expiresAt` DATETIME(3) NOT NULL,
  `mutationSet` JSON NULL,
  `mutationsDigest` VARCHAR(71) NULL,
  `commitDate` DATETIME(3) NULL,
  `expectedTreeSha` CHAR(40) NULL,
  `expectedCommitSha` CHAR(40) NULL,
  `receiptDigest` VARCHAR(71) NULL,
  `completedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `cp_fleet_cleanup_execution_capability_key` (`capabilityId`),
  UNIQUE INDEX `cp_fleet_cleanup_execution_key` (`executionKey`),
  UNIQUE INDEX `cp_fleet_cleanup_reservation_key` (`reservationId`),
  INDEX `cp_fleet_cleanup_execution_authority_state` (`authorityId`, `state`, `expiresAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `cp_fleet_cleanup_execution_authority_fkey` FOREIGN KEY (`authorityId`) REFERENCES `control_plane_fleet_cleanup_authority` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `cp_fleet_cleanup_execution_capability_fkey` FOREIGN KEY (`capabilityId`) REFERENCES `control_plane_fleet_cleanup_capability` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `control_plane_fleet_cleanup_execution_step` (
  `id` VARCHAR(191) NOT NULL,
  `executionId` VARCHAR(191) NOT NULL,
  `kind` VARCHAR(32) NOT NULL,
  `ordinal` INTEGER NOT NULL,
  `operationId` VARCHAR(71) NOT NULL,
  `state` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  `receiptDigest` VARCHAR(71) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `cp_fleet_cleanup_step_kind_key` (`executionId`, `kind`),
  UNIQUE INDEX `cp_fleet_cleanup_step_ordinal_key` (`executionId`, `ordinal`),
  UNIQUE INDEX `cp_fleet_cleanup_step_operation_key` (`executionId`, `operationId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `cp_fleet_cleanup_step_execution_fkey` FOREIGN KEY (`executionId`) REFERENCES `control_plane_fleet_cleanup_execution` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
