ALTER TABLE `app_metric_daily`
  ADD COLUMN `adCtaUsers` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `adCtaImpressions` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `adCompletedUsers` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `adCompletions` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `networkAdUsers` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `networkAdImpressions` INTEGER NOT NULL DEFAULT 0;
