---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backoffice-control-plane-snapshot-signing
  namespace: platform
spec:
  encryptedData:
    CONTROL_PLANE_SNAPSHOT_SIGNING_KEY: AgAHRFpaRTLjXj6LWzTmVjdsM6cXQuvyCQO3Y34n7XN1kqo0kHc5oIYao1RcaKar/SnTKFahNHq55nXqCvX+PJsy/E8cft/kAVUPfhtyjYZ90kAJai13sqdtwimWlMw4WSjawhjqsq6NJ2n9OVHRF5AVVErWALbnSvCqarM8y5o+WiWLf0j97PeYkX17a/IdswaPnQV3sJa11dXnYuRvaG6Y3V2anPeAHqWQah8IZQiKXtkHIbcXS28+u20y17xk4d9dDU3majqTxQd38CDda+0hzqqmJS33GTF2dNj39HCSc343iSeL/3JsN0fmHu+muUKVol1Wr1pAIc048XvjmihK7T9m75diu/Y9STFdApVdFsX1Q+IcUotRh/tyCxWdQSJOEou/EBZAwsNSPiZZVWOg/riKIChFVeUB2XOd9x88vZNM3w3E3HRDwrLYAstmp3EerCUfr6Ym+QIU1HWQJw625uqY8nSYRFUcROiTQHWi+7TqJhp86Lbj5oO7/LPa/cuUxolHJSEQj4b+rdy5ajTn3L1EQDDj6GEiiam+u9OVvBJraAsgj1LL3GQ6P648jt9q79ZUg7efC8TOAMYJWUO11hA2UdxQu4kOC7Qq54Akgm1yXm/IhfHBnycZu1Hhlf/unr0nU3oHOnwgBj2ZL9U9TM9Zh1l2EQs5Shf9DcMH25D3fqqTKX+8cB5WqhpaNSvxFbSNqx1nTmo1lUjF9lPvj7joM6W6EgNIRGyPDX4TcqgQftg9/xUqXkttkOhIveRLPqvAQ59pOiBZMW1cfdpQ
  template:
    metadata:
      name: backoffice-control-plane-snapshot-signing
      namespace: platform
