---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: platform-deployment-approvers
  namespace: platform
spec:
  encryptedData:
    2772002.token: AgBJrJ1ANa1U6ggvlAhNGxiNPoq9845p+64rC10AHTVgDaYZ7tbl0TOZYL10RzYg6TiMZYW3P96z8lOkR+p5yiV+eNb15bNDUGSDPuOKDxWNKJQRTvaq2yEJP/GBPSy9Kcnj9lNuRbj6izzl3apXCufUkPtxHRtawgtphZAhAu9L2JC9ooOFJgBoryWYRAd/aMWlZxMauMO5l5lBsjNCv6T55HT7NBkIu9bhcTR7R2Kyrohf0gxLTX+DsUCaaO44wvkA51tCk5LDmy/Uw2dPuRCOEsqg46xlu03OkWHQAK3mNWRUkh14rdpsCrUAV2WxpS4+QN1idBurWoHwEsfurjVWUa7mPLz0Vcaeu7FcTCDgB6TfpmadX3Ko6TwSesV/wDpzUiCpYUL3QD1XEB5Rvd0GWLZKw9ehUCrQH2sQSqQhRA8T7eAbbmpjg9RuqcA3jwuH9dY4hTyQYYUhiGlZj5UIcQRZW6fmuJI3LS5wGYc4/e3eonW0BfvM/L0bx98ZjlFZdZM/2gYwBScerEqG83ueeAq2eHCfBWzJecaorvw+kMhTUYU1H7dcA+jFEMVee4AxS3sFOGDCRQMgfoBpBhvftio2LvGuoKwtBDt0rymtos2RfWVfv11DSm0TOZ0JZre7c12DMgJc4apwtWeRG1VGKi2q40barTdaZO8rJDbaHucU63rzfMqD9h3swRk0mnYSSw7Oi0nSyBFs0yWIq1wDLqQdyP8+4ql0chAhR2Ws7F9HjE00xQME02xYqrpsELcAo3RqHOojgBAuBJ+Jynde6kKJlJuF6kn+18FUCwjVfuI56XpUvN6Sd/SG/5yn
  template:
    metadata:
      name: platform-deployment-approvers
      namespace: platform
    type: Opaque
